38 chrome bug
cesn4/discovery-app-learning pull request #59
Opened 2020-02-19 02:21 UTC by cesn4

Kaip viskas i rok :D, tik klasuimas jeigu noreciau transitiona uzmest ant tokio tai padavimo varu. Tai sugalvojau tik, kadIcon componente ji vel paduoti atgal i scss :D bet neskamba tai labai logiskai, kai specialiai issikelem varus i js. :D

2020-02-19 06:46 UTC, RokasAnisas requested changes

2020-02-19 06:46 UTC, RokasAnisas commented on src/components/Icons/Icon.tsx
> +                return <SVGInstagram {...iconProps} color={color} />;
`color` ir taip paduodamas kartu su `{...iconProps}`

2020-02-19 06:46 UTC, RokasAnisas commented on src/components/SocialButton/SocialButton.tsx
> +import { IconType } from '~/components/Icons/Icon';
importu orderis!

2020-02-19 06:46 UTC, RokasAnisas commented on src/components/SocialButton/SocialButton.tsx
> +        <div className={className}>
Šitas `div` nereikalingas

2020-02-19 06:46 UTC, RokasAnisas commented on src/components/Input/Input.scss
> +        outline: none;
Nauji standartai sako kad reikia palikt outline, kad žmonėms su negalia būtų lengviau naviguoti puslapį. Yra useriu kurie nenaudoja peles naršyt. Jei panaikini outline, turi nurodyt kita būda kuris indikuos focus state.

2020-02-25 15:23 UTC, cesn4 commented on src/components/Input/Input.scss
> +        outline: none;
oh okay :D, bet sitas outline buvo atrades tik, ant chrome, ant fireFoxo net nesimato :D

2020-02-26 08:34 UTC, RokasAnisas approved these changes

2020-02-26 15:04 UTC, merged