45 tests
cesn4/discovery-app-learning pull request #64
Opened 2020-02-21 10:26 UTC by cesn4

2020-02-22 09:48 UTC, RokasAnisas requested changes

2020-02-22 09:48 UTC, RokasAnisas commented on src/components/FeaturedCard/__tests__/FeaturedCard.test.tsx
> +const HappyProps: FeaturedCardProps = {
keep it consistant maciau vietom `happyProps` kitur su didziaja pradedi `HappyProps`, butu gerai suvienodint.

2020-02-22 09:48 UTC, RokasAnisas commented on src/components/Icons/__tests__/Icon.test.tsx
> +    it('Should render text', () => {
`..text`? koki teksta Icon renderina ? :D

2020-02-22 09:48 UTC, RokasAnisas commented on src/components/Icons/__tests__/Icon.test.tsx
> +        expect(wrapper.find(SVGFacebook)).toBeTruthy();
False positive, nesvaarbu ka paduosi kaip name, vistiek passins, not good, kiauras testas :D

2020-02-22 09:51 UTC, RokasAnisas requested changes

2020-02-22 09:51 UTC, RokasAniss commented on src/components/Author/__tests__/Author.test.tsx
> +    it('Should not have big if big prop is not passed', () => {
1. dukart taip pat vadinasi testas, bet dviem skirtingam divam checkini ar turi modifieri, siulyciau pervadint antra i `author-name has modifier -big`

2. Kad jau testuoji happy path, kad neisrenderina -big jei nepaduodi, sveika butu ir patestuot kad prideda `-big` jei paduodi propsa

2020-02-24 12:36 UTC, cesn4 commented on src/components/Icons/__tests__/Icon.test.tsx
> +        expect(wrapper.find(SVGFacebook)).toBeTruthy();
joa, patikrinau katik. Galvojau biski kitaip veiks jis :D

2020-02-26 09:16 UTC, RokasAnisas approved these changes

2020-02-26 15:04 UTC, merged