40 search section
cesn4/discovery-app-learning pull request #66
Opened 2020-02-26 18:11 UTC by cesn4

Uzsidejau pora TODO biskuti cia. Tingiu kolkas prie to sedeti :D, norisi page pasibaigti greiciau.

2020-03-02 07:21 UTC, RokasAnisas commented on src/sections/DiscoveryHero/DiscoveryHero.scss
> +            padding: spacer(trojan-xs) 170px;
`170px`  maciau egzistuoja prie spaceriu

2020-03-02 07:21 UTC, RokasAnisas commented on src/sections/DiscoveryHero/DiscoveryHero.scss
> +            padding: 150px spacer(trojan-xs);
`170px` egzistuoja prie spaceriu, 150px gal irgi pridet tada ?

2020-03-02 07:21 UTC, RokasAnisas commented on src/sections/DiscoveryHero/DiscoveryHero.scss
> +            padding: 150px spacer(trojan-xs);
`170px` egzistuoja prie spaceriu, 150px gal irgi pridet tada ?

2020-03-02 07:21 UTC, RokasAnisas commented on src/components/InputDropdown/InputDropdown.scss
> +        margin-bottom: 10px;
spacer ?

2020-03-02 07:21 UTC, RokasAniss commented on src/components/DiscoverySearch/DiscoverySearch.scss
> +    height: 100%;
optional: `size(100%);`

2020-03-02 07:22 UTC, RokasAnisas requested changes

2020-03-02 07:22 UTC, RokasAniss commented on src/components/DiscoveryTitle/DiscoveryTitle.scss
> +
2 empy lines per daug

2020-03-02 07:24 UTC, RokasAnisas requested changes

2020-03-02 07:24 UTC, RokasAniss commented on src/components/DiscoverySearch/DiscoverySearch.tsx
> +import SimpleButton from '../SimpleButton';
relative import? Not a child, naudok`~/`

2020-03-02 23:42 UTC, cesn4 commented on src/sections/DiscoveryHero/DiscoveryHero.scss
> +            padding: spacer(trojan-xs) 170px;
Damn sitie spaceriai pareina is Hero, kai yra jie jau sutvarkyti ten. Hero ismerginau tada dar nepatvarkyta, kad matyciau bendra vaizda matyciau.

2020-03-02 23:50 UTC, cesn4 commented on src/components/DiscoveryTitle/DiscoveryTitle.scss
> +
Sitas irgi dublikuojas :/

2020-03-03 07:27 UTC, RokasAnisas requested changes

2020-03-03 07:27 UTC, RokasAnisas commented on src/components/DiscoverySearch/DiscoverySearch.tsx
> +const DiscoverySearch: FunctionComponent = () => {
Unit test

2020-03-03 07:27 UTC, RokasAniss commented on src/components/InputDropdown/InputDropdown.tsx
> +            <span className={`${className}__label`}>Select date</span>
`InputDropdown` bet ihardcodintas select date, labai jau specifiska :D

2020-03-03 07:27 UTC, RokasAniss commented on src/components/InputDropdown/InputDropdown.tsx
> +            <Select options={options}></Select>
Siulyciau atskirai susikurt `~/components/Select` kuris bus kaip wrapperis sitam `react-select` komponentui, kur ji perstylinsi pagal puslapio dizaina.

2020-03-04 16:48 UTC, RokasAnisas requested changes

2020-03-04 16:48 UTC, RokasAniss commented on src/components/InputLabel/InputLabel.tsx
> +    name: InputType;
`InputLabel name=` gal netinkamas propsas nustatyt tipui, `Icon` tiko nes icon gali tiketis ka reiks name. O cia tu turi omeny kazka kito, tipa. Net ir value vadinasi `InputType`, tai siulyciau pervadinti i type.

2020-03-04 17:00 UTC, RokasAnisas requested changes

2020-03-04 17:00 UTC, RokasAnisas commented on src/components/InputLabel/Inputs/DropdownInput/DropdownInput.tsx
> +interface DropdownINputProps {
DropdownI**N**putProps -> DropdownInputProps

2020-03-04 17:00 UTC, RokasAnisas commented on src/components/InputLabel/Inputs/SimpleInput/SimpleInput.tsx
> +// TODO change png files to svg //
Kaip su situo todo ?

2020-03-06 08:22 UTC, RokasAnisas requested changes

2020-03-06 08:22 UTC, RokasAniss commented on src/components/DiscoverySearch/DiscoverySearch.tsx
> +                {/* TODO re-do hover */}
Ka su situo darom ?

2020-03-06 08:22 UTC, RokasAniss commented on src/components/InputLabel/Inputs/DropdownInput/DropdownInput.tsx
> +    // TODO make a props for this one ( react-select doesnt accept undefined )
Ka su situo darom ?

2020-03-08 13:06 UTC, cesn4 commented on src/components/DiscoverySearch/DiscoverySearch.tsx
> +                {/* TODO re-do hover */}
Pasikursiu taska kur improvinsiu visus hoverius i guess, nes ten ir dropdownui reikia refaktorinimo, next story irgi. Kolkas noriu kad veiktu viskas kaip priklauso :D

2020-03-08 13:06 UTC, cesn4 commented on src/components/InputLabel/Inputs/DropdownInput/DropdownInput.tsx
> +    // TODO make a props for this one ( react-select doesnt accept undefined )
Kai ka sugalvojau tuoj pameginsiu :D

2020-03-08 20:15 UTC, RokasAnisas approved these changes

2020-03-08 21:04 UTC, merged