37 author notes
cesn4/discovery-app-learning pull request #67
Opened 2020-02-27 00:27 UTC by cesn4

2020-03-02 08:46 UTC, RokasAnisas requested changes

2020-03-02 08:46 UTC, RokasAnisas commented on src/components/ExtraNavigation/ExtraNavigation.tsx
> +                                <Icon name="back" size={16} color="#343638" />
Pasikurk `~/constants/Colors.ts` kur uznaudosi exportuotas spalvas is `res/colors.scss`

2020-03-02 08:46 UTC, RokasAniss commented on src/components/Article/Article.tsx
> +    notes = undefined,
jeigu priskiri tipa boolean, tai default verte padaryk `true` arba `false` nes boolean tokia ir esme kad jis gali but 0 | 1.

2020-03-02 08:52 UTC, RokasAniss commented on src/components/Article/Article.scss
> +                column-count: 2;
Nice sitas, nesu naudojes dar niekad ! :D

2020-03-03 00:11 UTC, cesn4 commented on src/components/ExtraNavigation/ExtraNavigation.tsx
> +                                <Icon name="back" size={16} color="#343638" />
Sitas irgi parejas is ExtraNavigation

2020-03-03 00:13 UTC, cesn4 commented on src/components/Article/Article.scss
> +                column-count: 2;
Cool reikalas visai. :D,

2020-03-03 07:29 UTC, RokasAnisas requested changes

2020-03-03 07:29 UTC, RokasAniss commented on src/components/Article/Article.tsx
> +    subtitle,
visi propsai optional. Ka darys komponentas kai ji uznaudosi ir nieko nepaduosi ? :D

2020-03-04 14:37 UTC, cesn4 commented on src/components/Article/Article.tsx
> +    subtitle,
Good point, nebeatsimenu kodel taip padariau :D, nujamu nu content, nes jis visalaika reikalingas :D

2020-03-05 09:05 UTC, RokasAnisas requested changes

2020-03-05 09:05 UTC, RokasAniss commented on src/components/ExtraNavigation/ExtraNavigation.scss
> +            padding: 12px;
spacer?

2020-03-05 09:05 UTC, RokasAniss commented on src/components/ExtraNavigation/ExtraNavigation.scss
> +            border-radius: 6px;
radius var?

2020-03-05 09:05 UTC, RokasAniss commented on src/components/ExtraNavigation/ExtraNavigation.scss
> +            border: solid 2px;
border var ?

2020-03-05 09:59 UTC, cesn4 commented on src/components/ExtraNavigation/ExtraNavigation.scss
> +            padding: 12px;
Visi sitie sutvarkyti ExtraNavigatione :), naudojau ji kad ant naujo layouto viska statyciau.

2020-03-06 08:19 UTC, RokasAnisas approved these changes

2020-03-08 21:09 UTC, merged